### ISSUE TITLE
Make scipy an optional dependency

### ISSUE THREAD

**Issue by svisser** [JohannesBuchner/imagehash#4]
Currently both numpy and scipy are needed to install imagehash but this only makes sense when you're using the phash function. If you're using average_hash or dhash then you only need numpy.

Hence scipy should be marked as an optional dependency, both in the code and in setup.py.

People can then install this library as needed by using, e.g., `pip install ImageHash` or `pip install ImageHash[pHash]` using the optional dependency functionality.

**Comment by gustavofuhr** [comment]
Up to that!

**Comment by JohannesBuchner** [comment]
Sorry, this is a WONTFIX for me, because I see phash as core functionality. If that is a problem for you, it is easy enough to rip it out and install the package locally. 
For my own information, here is how one could implement that: https://stackoverflow.com/questions/10572603/specifying-optional-dependencies-in-pypi-python-setup-py
