### ISSUE TITLE
Small images on whash

### ISSUE THREAD

**Issue by ChristopherGondek** [JohannesBuchner/imagehash#45]
If whash(image, hash_size = 8, image_scale = None, mode = 'haar', remove_max_haar_ll = True) is called on a very small image it gives an "AssertionError: hash_size in a wrong range".
This is hard to track down, since called with default parameter values and the docstring states:

@hash_size must be a power of 2 and less than @image_scale.
@image_scale must be power of 2 and less than image size. By default is equal to max power of 2 for an input image.

I suggest a different AssertionError message for small images and "image_scale is None"

**Comment by dmpetrov** [comment]
Hi Christopher,

Most likely it is related to the image ratio, not size.

I'll take a look today night. It would be great if you send me an image example.

Thanks,
Dmitry Petrov
Email: dmitry.petrov@nevesomo.com

**Comment by ChristopherGondek** [comment]
Hi Dmitry,

I sent you an example. But you can take any image with a size e.g. 9 by 4 pixels.
Probably many people will use whash on unseen images.

**Comment by dmpetrov** [comment]
Hey Christopher and Johannes,

Yeah, it is an interesting example... Images with default image_scale less
than default hash_size (one of the dimensions is less than 7) become a
problem. There are three solutions:
1) Adjust images size to hash_size=8 - a special case for small images.
2) Reduce default hash_size - a special case for small images.
3) Keep as is and a user should decide what is the best for his scenario.

I'd say that  (2) is a very bad option since it affects output data format
and you might loose compatibility with your other hashes.
(3) is okay and previously I've decided it is the best because of the small
images is a very special case and a user should decide what to do.

Now, I agree with you ("Probably many people will use whash on unseen
images.") and I would implement (1).

The fix is straightforward:

line
image_scale = 2**int(numpy.log2(min(image.size)))

has to be replaced to:
image_natural_scale = 2**int(numpy.log2(min(image.size)))
image_scale = max(image_natural_scale, hash_size)

How do you think guys? Should I publish the change?


--
Thanks,
Dmitry Petrov

**Comment by ChristopherGondek** [comment]
I vote for (1) and agree that (2) is a bad option.
Maybe we can add a warning? Due to the upscaling, information is duplicated and that should be considered in the distance evaluation of hashes in any further processing.

**Comment by JohannesBuchner** [comment]
This is only a problem in whash? I think imagehash is supposed to greyscale and resize images to the hashsize. Do I understand correctly that this is the problem in whash with too-small-images?

@dmpetrov, that seems reasonable. Also agree with @ChristopherGondek, perhaps a warning is useful.

Guys, you are awesome, I don't have to do anything any more with this project :)

**Comment by ChristopherGondek** [comment]
Correct. Only whash is affected with images that are too small.
Btw. you are also awesome, @JohannesBuchner, this package is really helping my thesis :+1: .
But credit goes to all contributors. Thanks!

I wrote unit tests for all hashes. I can make a pull request if you like.

**Comment by JohannesBuchner** [comment]
@ChristopherGondek I don't see your unit tests. Are you sure you push these? 
Glad to see it is useful. It would be great to have a paper associated or using imagehash :)

**Comment by ChristopherGondek** [comment]
Yes, I did not push it. Pushed now. ChristopherGondek/imagehash

**Comment by dmpetrov** [comment]
Christopher, I don't see your change with this fix. Did you push the change?

**Comment by ChristopherGondek** [comment]
I created a pull request with unit tests. But with the two lines:

image_natural_scale = 2**int(numpy.log2(min(image.size)))
image_scale = max(image_natural_scale, hash_size)

Test test_hash_size_is_less_than_image_size will fail with these changes.

**Comment by dmpetrov** [comment]
@ChristopherGondek yeah, it makes sense since we use to have the solution (3) and the unit test for the solution fails. I fixed the unit-test and added one more. Please take a look at the pull request.

**Comment by ChristopherGondek** [comment]
@dmpetrov Looks good to me. 
Btw: Is it possible that we have some styling issues with space and tabs indents mixed, etc.? Looks like imagehash/__init__.py has all tabs and the rest has spaces. Can we make it consistent?

**Comment by JohannesBuchner** [comment]
Hi @ChristopherGondek,
could you please test version 3.3 from pypi and see if it works for you?
Thank you, Johannes

**Comment by dmpetrov** [comment]
Thanks @ChristopherGondek It looks like @JohannesBuchner fixed the tab indent issues and merged the change. I'll definitely test 3.3 today night.
 
Thank you guys!

**Comment by ChristopherGondek** [comment]
Thanks from my side as well! 
@JohannesBuchner as far as I can tell, everything is working fine in 3.3 for me. And thank you for fixing the indents.

**Comment by dmpetrov** [comment]
@JohannesBuchner 3.3 works well. Thank you!

**Comment by JohannesBuchner** [comment]
Thanks
