### ISSUE TITLE
Having ImageHash instances be iterable would be awesome!

### ISSUE THREAD

**Issue by fake-name** [JohannesBuchner/imagehash#5]
A nice tweak would be to make it possible to iterate over the values in ImageHash instances.

This makes things like converting to non-hex string representations much easier. 

For example, I currently want to convert the hash value into a string of "1" or "0" values, for use in a database (I can use the DB's fuzzy text matching with such a string).

Currently, I have to:
```
dHash = "".join(["1" if val else "0" for val in np.nditer(dHash.hash, order='C') ])
```
which means I need numpy imported in my own code, and it's just ugly.

I think this could be as simple as just adding:
```
	def __iter__(self):
		return np.nditer(self.hash, order='C')
```
to the ImageHash class (I'm not totally sure you can *return* an iterator object for the iterator class method), but even if not, it should only be a few lines.

At that point, my own code is the much more clean:
```
dHash = "".join(["1" if val else "0" for val in dHash ])
```

**Comment by JohannesBuchner** [comment]
I will close this, because the original problem I think is solved. I think the  ```__hash__``` implementation is ok (looking at https://stackoverflow.com/questions/4005318/how-to-implement-a-good-hash-function-in-python and https://docs.python.org/2/reference/datamodel.html#object.__hash__, the requirements for ```__hash__``` are very weak). If you are unhappy about the performance, please open a new bug and document the problem you experience. Thank you.

**Comment by fake-name** [comment]
Ok, that's fine.

I've migrated to using the 64-bit integer representation of the hash in a custom tree system (BK-tree) at this point, so it's somewhat irrelevant anyways.
